version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  add_product:
    build:
      context: ./backend/add_product
    container_name: add_product_service
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  checkout:
    build:
      context: ./backend/checkout
    container_name: checkout_service
    ports:
      - "4002:4002"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  delete_product:
    build:
      context: ./backend/delete_product
    container_name: delete_product_service
    ports:
      - "4003:4003"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  get_cart:
    build:
      context: ./backend/get_cart
    container_name: get_cart_service
    ports:
      - "4005:4005"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  login:
    build:
      context: ./backend/login
    container_name: login_service
    ports:
      - "4006:4006"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  register:
    build:
      context: ./backend/register
    container_name: register_service
    ports:
      - "4007:4007"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  reset_cart:
    build:
      context: ./backend/reset_cart
    container_name: reset_cart_service
    ports:
      - "4008:4008"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  search_products:
    build:
      context: ./backend/search_products
    container_name: search_products_service
    ports:
      - "4009:4009"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  sort_cart:
    build:
      context: ./backend/sort_cart
    container_name: sort_cart_service
    ports:
      - "4010:4010"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  update_quantity:
    build:
      context: ./backend/update_quantity
    container_name: update_quantity_service
    ports:
      - "4011:4011"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  get_products:
    build:
      context: ./backend/get_products
    container_name: get_products_service
    ports:
      - "4012:4012"
    environment:
      - MONGO_URI=${MONGO_URI}
    restart: always
    depends_on:
      - mongo

  add_product_nodejs:
    build:
      context: ./nodejs-services/add_product
    container_name: add_product_nodejs_service
    ports:
      - "5007:5000"
    restart: always

  delete_product_nodejs:
    build:
      context: ./nodejs-services/delete_product
    container_name: delete_product_nodejs_service
    ports:
      - "5001:5001"
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend_service
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    restart: always

volumes:
  mongo-data: