name: CI/CD Pipeline for Delete Product Node.js Service

on:
  push:
    branches:
      - QA

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./nodejs-services/delete_product
        push: true
        tags: fernando615/delete_product_nodejs_service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_DELETE_PRODUCT_NODEJS }}
        username: ${{ secrets.EC2_USER_DELETE_PRODUCT_NODEJS }}
        key: ${{ secrets.EC2_KEY_DELETE_PRODUCT_NODEJS }}
        port: 22
        script: |
          docker stop delete_product_nodejs_service || true
          docker rm delete_product_nodejs_service || true
          docker pull fernando615/delete_product_nodejs_service:latest
          docker run -d -p 4015:4015 --name delete_product_nodejs_service fernando615/delete_product_nodejs_service:latest