name: CI/CD Pipeline for Register Service

on:
  push:
    branches:
      - QA

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/register
        push: true
        tags: fernando615/register_service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_REGISTER }}
        username: ${{ secrets.EC2_USER_REGISTER }}
        key: ${{ secrets.EC2_KEY_REGISTER }}
        port: 22
        script: |
          docker stop register_service || true
          docker rm register_service || true
          docker pull fernando615/register_service:latest
          docker run -d -p 4007:4007 --name register_service \
            -e MAIL_SERVER=smtp.gmail.com \
            -e MAIL_PORT=587 \
            -e MAIL_USE_TLS=True \
            -e MAIL_USERNAME=tu_correo@gmail.com \
            -e MAIL_PASSWORD=tu_contraseña_de_gmail \
            -e MAIL_DEFAULT_SENDER=tu_correo@gmail.com \
            -e SECRET_KEY=your_secret_key \
            fernando615/register_service:latest