name: CI/CD Pipeline for Search Products Service

on:
  push:
    branches:
      - QA

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./backend/search_products
        push: true
        tags: fernando615/search_products_service:latest

  deploy:
    runs-on: ubuntu-latest    docker --version
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_SEARCH_PRODUCTS }}
        username: ${{ secrets.EC2_USER_SEARCH_PRODUCTS }}
        key: ${{ secrets.EC2_KEY_SEARCH_PRODUCTS }}
        port: 22
        script: |
          docker stop search_products_service || true
          docker rm search_products_service || true
          docker pull fernando615/search_products_service:latest
          docker run -d -p 4007:4007 --name search_products_service fernando615/search_products_service:latest